### ISSUE TITLE
Portrait mode

### ISSUE THREAD

**Issue by xmha97** [jamal2362/Mini-Car-Launcher#1]
Thanks for this app.
Please add portrait mode. (Instead of landscape)

![Screenshot_2023-03-03-02-59-02-163_com.jamal2367.minicarlauncher.jpg](https://user-images.githubusercontent.com/23485114/222587521-6a48be0d-6be3-4aee-8da2-ddae5f5a4a7b.jpg)

**Comment by jamal2362** [comment]
Hello,
this app is intended for vehicles that use the Android operating system.
This is not intended for smartphones.

**Comment by xmha97** [comment]
Thanks for your reply 🙏
